server:
  port: 7000
  servlet:
    context-path: /

management:
  health:
    redis:
      enabled: false

rpc:
  producer: http://localhost:8000

feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 100
    connection-timeout: 2

  okhttp:
    enabled: true